// routes/report.js
const express = require('express');
const { chromium } = require('playwright');
const router  = express.Router();
const { requireClient, supabaseAdmin } = require('../middleware/authMiddleware');
const { generateBudgetXLSX } = require('../services/excelService');

async function ensureWeddingAccess(weddingId, profile) {
  const { data: wedding, error } = await supabaseAdmin
    .from('weddings')
    .select('id, client_id')
    .eq('id', weddingId)
    .single();

  if (error || !wedding) {
    return { ok: false, status: 404, error: 'Wedding not found.' };
  }

  if (wedding.client_id !== profile.id) {
    return { ok: false, status: 403, error: 'Not authorised for this wedding.' };
  }

  return { ok: true, wedding };
}

// ── XLSX Export ────────────────────────────────────────────────────────────
// POST /api/report/xlsx
router.post('/xlsx', requireClient, async (req, res) => {
  try {
    const { items = [], summary = {}, meta = {}, actuals = [] } = req.body;
    const buffer = await generateBudgetXLSX({ items, summary, meta, actuals });
    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    res.setHeader('Content-Disposition', 'attachment; filename="WeddingBudget_Estimate.xlsx"');
    res.send(buffer);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});
// POST /api/report/pdf — generate PDF, return as buffer
router.post('/pdf', requireClient, async (req, res) => {
  try {
    // Generate HTML for PDF
    const { items, summary, meta, inputs } = req.body;
    const fmt = n => '₹' + Number(n).toLocaleString('en-IN');
    const CAT_COLORS = ['#7a1c1c','#a0522d','#c68642','#d4a843','#8b6914','#5a3e28'];

    const html = `<!DOCTYPE html><html><head><meta charset="UTF-8">
    <style>
      body { font-family: 'Georgia', serif; color: #1a0a0a; background: #fff; padding: 40px; max-width: 800px; margin: 0 auto; }
      h1 { font-size: 32px; color: #7a1c1c; margin: 0 0 4px; }
      .sub { font-size: 12px; color: #888; letter-spacing: 2px; text-transform: uppercase; margin-bottom: 32px; }
      .summary { display: flex; gap: 24px; margin-bottom: 32px; padding: 24px; background: #7a1c1c; border-radius: 8px; color: #E8C97A; text-align: center; }
      .summary-item { flex: 1; }
      .summary-label { font-size: 10px; letter-spacing: 2px; text-transform: uppercase; opacity: 0.7; }
      .summary-value { font-size: 24px; font-weight: bold; margin-top: 4px; }
      .item { padding: 16px; border: 1px solid #f0e8e0; border-radius: 8px; margin-bottom: 10px; display: flex; justify-content: space-between; }
      .item-cat { font-weight: bold; font-size: 14px; }
      .item-sub { font-size: 11px; color: #888; margin-top: 2px; }
      .item-cost { text-align: right; font-size: 16px; font-weight: bold; color: #7a1c1c; }
      .item-pct { font-size: 11px; color: #888; }
      .footer { margin-top: 32px; font-size: 11px; color: #aaa; text-align: center; border-top: 1px solid #f0e8e0; padding-top: 16px; }
    </style></head><body>
    <h1>WeddingBudget.ai — Estimate Report</h1>
    <div class="sub">${meta?.city ?? ''} · ${meta?.hotelLabel ?? ''} · ${meta?.guests ?? 0} Guests · ${new Date().toLocaleDateString('en-IN')}</div>
    <div class="summary">
      <div class="summary-item"><div class="summary-label">Conservative</div><div class="summary-value">${fmt(summary?.conservative ?? 0)}</div></div>
      <div class="summary-item"><div class="summary-label">Expected</div><div class="summary-value">${fmt(summary?.expected ?? 0)}</div></div>
      <div class="summary-item"><div class="summary-label">Luxury</div><div class="summary-value">${fmt(summary?.luxury ?? 0)}</div></div>
    </div>
    ${(items ?? []).map((item, i) => `
    <div class="item">
      <div><div class="item-cat">${item.cat}</div><div class="item-sub">${item.sub ?? ''}</div></div>
      <div><div class="item-cost">${fmt(item.min)} – ${fmt(item.max)}</div><div class="item-pct">${item.pct ?? 0}% of total</div></div>
    </div>`).join('')}
    <div class="footer">Generated by WeddingBudget.ai · All estimates are indicative ranges · Actual costs may vary based on vendor negotiations, season and availability</div>
    </body></html>`;

    // Use Playwright to render HTML to PDF
    let pdfBuffer;
    let browser;
    try {
      browser = await chromium.launch({ headless: true, args: ['--no-sandbox', '--disable-setuid-sandbox'] });
      const page = await browser.newPage();
      await page.setContent(html, { waitUntil: 'networkidle0' });
      pdfBuffer = await page.pdf({ format: 'A4', printBackground: true, margin: { top: '20mm', bottom: '20mm', left: '15mm', right: '15mm' } });
    } catch (pdfError) {
      return res.status(503).json({ error: `PDF engine unavailable: ${pdfError.message}` });
    } finally {
      if (browser) {
        await browser.close();
      }
    }

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', 'attachment; filename="WeddingBudget_Estimate.pdf"');
    res.send(pdfBuffer);

  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ── Budget Actuals (tracker) ───────────────────────────────────────────────
// GET /api/report/actuals/:weddingId
router.get('/actuals/:weddingId', requireClient, async (req, res) => {
  const access = await ensureWeddingAccess(req.params.weddingId, req.profile);
  if (!access.ok) return res.status(access.status).json({ error: access.error });

  const { data, error } = await supabaseAdmin
    .from('budget_actuals')
    .select('*')
    .eq('wedding_id', req.params.weddingId)
    .order('created_at', { ascending: false });
  if (error) return res.status(500).json({ error: error.message });
  res.json({ actuals: data ?? [] });
});

// POST /api/report/actuals — log an actual spend
router.post('/actuals', requireClient, async (req, res) => {
  const { weddingId, estimateId, cost_head, line_item_label, estimated_min, estimated_max, actual_amount, vendor_name, invoice_reference, paid_date, notes } = req.body;
  if (!weddingId || !cost_head || !line_item_label) return res.status(400).json({ error: 'weddingId, cost_head, line_item_label required.' });

  const access = await ensureWeddingAccess(weddingId, req.profile);
  if (!access.ok) return res.status(access.status).json({ error: access.error });

  const { data, error } = await supabaseAdmin.from('budget_actuals').insert({
    wedding_id: weddingId, estimate_id: estimateId ?? null, cost_head, line_item_label,
    estimated_min: estimated_min ?? null, estimated_max: estimated_max ?? null,
    actual_amount: actual_amount ?? null, vendor_name: vendor_name ?? null,
    invoice_reference: invoice_reference ?? null, paid_date: paid_date ?? null,
    notes: notes ?? null, logged_by: req.profile.id,
  }).select().single();

  if (error) return res.status(500).json({ error: error.message });
  res.status(201).json({ actual: data });
});

// PUT /api/report/actuals/:id
router.put('/actuals/:id', requireClient, async (req, res) => {
  // Verify ownership before updating
  const { data: existing, error: fetchError } = await supabaseAdmin
    .from('budget_actuals')
    .select('wedding_id, weddings!inner(client_id)')
    .eq('id', req.params.id)
    .single();
  if (fetchError || !existing) return res.status(404).json({ error: 'Actual not found.' });
  if (existing.weddings.client_id !== req.profile.id) {
    return res.status(403).json({ error: 'Not authorised to edit this record.' });
  }

  const allowed = ['actual_amount', 'vendor_name', 'invoice_reference', 'paid_date', 'notes'];
  const updates = {};
  allowed.forEach(k => { if (req.body[k] !== undefined) updates[k] = req.body[k]; });
  updates.updated_at = new Date().toISOString();
  const { data, error } = await supabaseAdmin.from('budget_actuals').update(updates).eq('id', req.params.id).select().single();
  if (error) return res.status(500).json({ error: error.message });
  res.json({ actual: data });
});

// DELETE /api/report/actuals/:id
router.delete('/actuals/:id', requireClient, async (req, res) => {
  // Verify ownership before deleting
  const { data: existing, error: fetchError } = await supabaseAdmin
    .from('budget_actuals')
    .select('wedding_id, weddings!inner(client_id)')
    .eq('id', req.params.id)
    .single();
  if (fetchError || !existing) return res.status(404).json({ error: 'Actual not found.' });
  if (existing.weddings.client_id !== req.profile.id) {
    return res.status(403).json({ error: 'Not authorised to delete this record.' });
  }

  const { error } = await supabaseAdmin.from('budget_actuals').delete().eq('id', req.params.id);
  if (error) return res.status(500).json({ error: error.message });
  res.json({ message: 'Deleted.' });
});

// GET /api/report/scenarios/:weddingId
router.get('/scenarios/:weddingId', requireClient, async (req, res) => {
  const access = await ensureWeddingAccess(req.params.weddingId, req.profile);
  if (!access.ok) return res.status(access.status).json({ error: access.error });

  const { data, error } = await supabaseAdmin
    .from('scenarios')
    .select(`*, budget_estimates ( id, total_min, total_max, total_mid, line_items ), cities ( label ), hotel_tiers ( label )`)
    .eq('wedding_id', req.params.weddingId)
    .order('created_at', { ascending: false });
  if (error) return res.status(500).json({ error: error.message });
  res.json({ scenarios: data ?? [] });
});

// POST /api/report/scenarios — save a scenario
router.post('/scenarios', requireClient, async (req, res) => {
  const { weddingId, label, cityId, hotelTierId, estimateId, isBaseline = false, notes } = req.body;
  if (!weddingId || !label?.trim()) return res.status(400).json({ error: 'weddingId and label are required.' });

  const access = await ensureWeddingAccess(weddingId, req.profile);
  if (!access.ok) return res.status(access.status).json({ error: access.error });

  let resolvedEstimateId = estimateId ?? null;
  if (!resolvedEstimateId) {
    const { data: currentEstimate } = await supabaseAdmin
      .from('budget_estimates')
      .select('id')
      .eq('wedding_id', weddingId)
      .eq('is_current', true)
      .order('generated_at', { ascending: false })
      .limit(1)
      .maybeSingle();
    resolvedEstimateId = currentEstimate?.id ?? null;
  }

  const { data, error } = await supabaseAdmin.from('scenarios').insert({
    wedding_id: weddingId,
    label: label.trim(),
    city_id: cityId ?? null,
    hotel_tier_id: hotelTierId ?? null,
    estimate_id: resolvedEstimateId,
    is_baseline: isBaseline,
    notes: notes ?? null,
  }).select(`*, budget_estimates ( id, total_min, total_max, total_mid, line_items ), cities ( label ), hotel_tiers ( label )`).single();
  if (error) return res.status(500).json({ error: error.message });
  res.status(201).json({ scenario: data });
});

// DELETE /api/report/scenarios/:id
router.delete('/scenarios/:id', requireClient, async (req, res) => {
  const { data: scenario, error: fetchErr } = await supabaseAdmin
    .from('scenarios')
    .select('id, wedding_id')
    .eq('id', req.params.id)
    .single();

  if (fetchErr || !scenario) return res.status(404).json({ error: 'Scenario not found.' });

  const access = await ensureWeddingAccess(scenario.wedding_id, req.profile);
  if (!access.ok) return res.status(access.status).json({ error: access.error });

  const { error } = await supabaseAdmin.from('scenarios').delete().eq('id', req.params.id);
  if (error) return res.status(500).json({ error: error.message });
  res.json({ message: 'Scenario deleted.' });
});

module.exports = router;