// routes/report.js
const express = require('express');
const router  = express.Router();
const { requireAuth, supabaseAdmin } = require('../middleware/authMiddleware');
const { generateBudgetXLSX } = require('../services/excelService');

// ── XLSX Export ────────────────────────────────────────────────────────────
// POST /api/report/xlsx
router.post('/xlsx', async (req, res) => {
  try {
    const { items = [], summary = {}, meta = {}, actuals = [] } = req.body;
    const buffer = await generateBudgetXLSX({ items, summary, meta, actuals });
    res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    res.setHeader('Content-Disposition', 'attachment; filename="WeddingBudget_Estimate.xlsx"');
    res.send(buffer);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});
// POST /api/report/pdf — generate PDF, return as buffer
router.post('/pdf', async (req, res) => {
  try {
    // Generate HTML for PDF
    const { items, summary, meta, inputs } = req.body;
    const fmt = n => '₹' + Number(n).toLocaleString('en-IN');
    const CAT_COLORS = ['#7a1c1c','#a0522d','#c68642','#d4a843','#8b6914','#5a3e28'];

    const html = `<!DOCTYPE html><html><head><meta charset="UTF-8">
    <style>
      body { font-family: 'Georgia', serif; color: #1a0a0a; background: #fff; padding: 40px; max-width: 800px; margin: 0 auto; }
      h1 { font-size: 32px; color: #7a1c1c; margin: 0 0 4px; }
      .sub { font-size: 12px; color: #888; letter-spacing: 2px; text-transform: uppercase; margin-bottom: 32px; }
      .summary { display: flex; gap: 24px; margin-bottom: 32px; padding: 24px; background: #7a1c1c; border-radius: 8px; color: #E8C97A; text-align: center; }
      .summary-item { flex: 1; }
      .summary-label { font-size: 10px; letter-spacing: 2px; text-transform: uppercase; opacity: 0.7; }
      .summary-value { font-size: 24px; font-weight: bold; margin-top: 4px; }
      .item { padding: 16px; border: 1px solid #f0e8e0; border-radius: 8px; margin-bottom: 10px; display: flex; justify-content: space-between; }
      .item-cat { font-weight: bold; font-size: 14px; }
      .item-sub { font-size: 11px; color: #888; margin-top: 2px; }
      .item-cost { text-align: right; font-size: 16px; font-weight: bold; color: #7a1c1c; }
      .item-pct { font-size: 11px; color: #888; }
      .footer { margin-top: 32px; font-size: 11px; color: #aaa; text-align: center; border-top: 1px solid #f0e8e0; padding-top: 16px; }
    </style></head><body>
    <h1>WeddingBudget.ai — Estimate Report</h1>
    <div class="sub">${meta?.city ?? ''} · ${meta?.hotelLabel ?? ''} · ${meta?.guests ?? 0} Guests · ${new Date().toLocaleDateString('en-IN')}</div>
    <div class="summary">
      <div class="summary-item"><div class="summary-label">Conservative</div><div class="summary-value">${fmt(summary?.conservative ?? 0)}</div></div>
      <div class="summary-item"><div class="summary-label">Expected</div><div class="summary-value">${fmt(summary?.expected ?? 0)}</div></div>
      <div class="summary-item"><div class="summary-label">Luxury</div><div class="summary-value">${fmt(summary?.luxury ?? 0)}</div></div>
    </div>
    ${(items ?? []).map((item, i) => `
    <div class="item">
      <div><div class="item-cat">${item.cat}</div><div class="item-sub">${item.sub ?? ''}</div></div>
      <div><div class="item-cost">${fmt(item.min)} – ${fmt(item.max)}</div><div class="item-pct">${item.pct ?? 0}% of total</div></div>
    </div>`).join('')}
    <div class="footer">Generated by WeddingBudget.ai · All estimates are indicative ranges · Actual costs may vary based on vendor negotiations, season and availability</div>
    </body></html>`;

    // Use puppeteer to render HTML to PDF
    let pdfBuffer;
    try {
      const puppeteer = require('puppeteer');
      const browser   = await puppeteer.launch({ headless: true, args: ['--no-sandbox', '--disable-setuid-sandbox'] });
      const page      = await browser.newPage();
      await page.setContent(html, { waitUntil: 'networkidle0' });
      pdfBuffer = await page.pdf({ format: 'A4', printBackground: true, margin: { top: '20mm', bottom: '20mm', left: '15mm', right: '15mm' } });
      await browser.close();
    } catch {
      // Puppeteer not available — return HTML instead
      res.setHeader('Content-Type', 'text/html');
      return res.send(html);
    }

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', 'attachment; filename="WeddingBudget_Estimate.pdf"');
    res.send(pdfBuffer);

  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ── Budget Actuals (tracker) ───────────────────────────────────────────────
// GET /api/report/actuals/:weddingId
router.get('/actuals/:weddingId', requireAuth, async (req, res) => {
  const { data, error } = await supabaseAdmin
    .from('budget_actuals')
    .select('*')
    .eq('wedding_id', req.params.weddingId)
    .order('created_at', { ascending: false });
  if (error) return res.status(500).json({ error: error.message });
  res.json({ actuals: data ?? [] });
});

// POST /api/report/actuals — log an actual spend
router.post('/actuals', requireAuth, async (req, res) => {
  const { weddingId, estimateId, cost_head, line_item_label, estimated_min, estimated_max, actual_amount, vendor_name, invoice_reference, paid_date, notes } = req.body;
  if (!weddingId || !cost_head || !line_item_label) return res.status(400).json({ error: 'weddingId, cost_head, line_item_label required.' });

  const { data, error } = await supabaseAdmin.from('budget_actuals').insert({
    wedding_id: weddingId, estimate_id: estimateId ?? null, cost_head, line_item_label,
    estimated_min: estimated_min ?? null, estimated_max: estimated_max ?? null,
    actual_amount: actual_amount ?? null, vendor_name: vendor_name ?? null,
    invoice_reference: invoice_reference ?? null, paid_date: paid_date ?? null,
    notes: notes ?? null, logged_by: req.profile.id,
  }).select().single();

  if (error) return res.status(500).json({ error: error.message });
  res.status(201).json({ actual: data });
});

// PUT /api/report/actuals/:id
router.put('/actuals/:id', requireAuth, async (req, res) => {
  const allowed = ['actual_amount', 'vendor_name', 'invoice_reference', 'paid_date', 'notes'];
  const updates = {};
  allowed.forEach(k => { if (req.body[k] !== undefined) updates[k] = req.body[k]; });
  updates.updated_at = new Date().toISOString();
  const { data, error } = await supabaseAdmin.from('budget_actuals').update(updates).eq('id', req.params.id).select().single();
  if (error) return res.status(500).json({ error: error.message });
  res.json({ actual: data });
});

// DELETE /api/report/actuals/:id
router.delete('/actuals/:id', requireAuth, async (req, res) => {
  const { error } = await supabaseAdmin.from('budget_actuals').delete().eq('id', req.params.id);
  if (error) return res.status(500).json({ error: error.message });
  res.json({ message: 'Deleted.' });
});

// GET /api/report/scenarios/:weddingId
router.get('/scenarios/:weddingId', requireAuth, async (req, res) => {
  const { data } = await supabaseAdmin.from('scenarios').select(`*, budget_estimates ( total_min, total_max, total_mid, line_items ), cities ( label ), hotel_tiers ( label )`).eq('wedding_id', req.params.weddingId);
  res.json({ scenarios: data ?? [] });
});

// POST /api/report/scenarios — save a scenario
router.post('/scenarios', requireAuth, async (req, res) => {
  const { weddingId, label, cityId, hotelTierId, estimateId, isBaseline = false, notes } = req.body;
  const { data, error } = await supabaseAdmin.from('scenarios').insert({
    wedding_id: weddingId, label, city_id: cityId ?? null, hotel_tier_id: hotelTierId ?? null,
    estimate_id: estimateId ?? null, is_baseline: isBaseline, notes: notes ?? null,
  }).select().single();
  if (error) return res.status(500).json({ error: error.message });
  res.status(201).json({ scenario: data });
});

module.exports = router;